### ISSUE TITLE
error checkout twrp 5.1

### ISSUE THREAD

**Issue by furinalover8236** [minimal-manifest-twrp/platform_manifest_twrp_omni#102]
error: Cannot checkout android: GitError: android rev-list ('^175f24d8823811909c45f58f8bd63debb3f888eb', 'HEAD', '--'): fatal: Not a git repository (or any of the parent directories): .git

**Comment by CaptainThrowback** [comment]
Follow the instructions in the README for using this repo. I just used it two days ago and it worked fine.
