### ISSUE TITLE
Error while compiling on MacOS

### ISSUE THREAD

**Issue by MarisaDAZA** [minimal-manifest-twrp/platform_manifest_twrp_omni#104]
After running all command in README.md, it returned this:
```
<source-dir>/twrp-8.1/build/soong/cmd/microfactory/microfactory.bash: line 85: <source-dir>/twrp-8.1/prebuilts/go/darwin-x86//bin/go: No such file or directory

#### failed to build some targets  ####
```

**Comment by MartinX3** [comment]
You use the macos branch?

**Comment by MarisaDAZA** [comment]
> You use the macos branch?

Well, I think the comands if them are the same in README.md

**Comment by MartinX3** [comment]
Please use the MacOS branch. :)

**Comment by MarisaDAZA** [comment]
> Please use the MacOS branch. :)

But how? There are no different between their README.md. And they still use *git://*
`repo init -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1`

**Comment by MartinX3** [comment]
Thank you for the hint.
It's fixed now. :)
