### ISSUE TITLE
export_includes', needed by import_includes', missing and no known rule to make it

### ISSUE THREAD

**Issue by thinksecure** [minimal-manifest-twrp/platform_manifest_twrp_omni#108]
Hello, is there is a way to fix this?
Not sure how to fix this by myself.
![Screenshot_20230605_175502](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/assets/108988761/49336e72-f567-4c24-8e0b-9efe62dacd2e)
Command Used: `cd /home/Username/TWRPProject/TWRP; export ALLOW_MISSING_DEPENDENCIES=true; . build/envsetup.sh; lunch omni_mh2lm-eng; mka bootimage`

**Comment by MartinX3** [comment]
Is it still a problem?
Then I'll reopen it.
