### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by ycly2333** [minimal-manifest-twrp/platform_manifest_twrp_omni#110]
I have built a twrp with twrp-7.1 branch by github action,but it made error when it is building.I could build it with the same tree,source and environment 2 months ago,but now it can't.
Log: https://github.com/ycly2333/Action-Recovery-builder/actions/runs/6906504020/job/18791680846
tree: https://github.com/ycly2333/android_device_EEBBK_H3000A-twrp

**Comment by CaptainThrowback** [comment]
This is not a manifest issue. You need to use the correct Action Builder.
