### ISSUE TITLE
Building repo command is wrong

### ISSUE THREAD

**Issue by Athwale** [minimal-manifest-twrp/platform_manifest_twrp_omni#117]
Here https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/tree/twrp-8.1 you are asked to use:
`repo init -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1`
which does not work and must be 
`repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1`

**Comment by CaptainThrowback** [comment]
Submit PR

**Comment by Athwale** [comment]
https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/pull/121
