### ISSUE TITLE
twrp-9.0: error building on whyred

### ISSUE THREAD

**Issue by mechakotik** [minimal-manifest-twrp/platform_manifest_twrp_omni#33]
`error: frameworks/base/libs/hwui/Android.bp:1:1: "hwui_defaults" depends on undefined module "skia_deps"
`

**Comment by MartinX3** [comment]
I only get it if I set `export ALLOW_MISSING_DEPENDENCIES=false;`
Did you set it to `true`?

**Comment by rajatgupta1998** [comment]
If anyone's still looking for the solution, the actual one is to sync external/skia repo.

Ref: https://android.googlesource.com/platform/external/skia/+/refs/tags/android-9.0.0_r61/Android.bp#940

**Comment by CaptainThrowback** [comment]
> If anyone's still looking for the solution, the actual one is to sync external/skia repo.
> 
> Ref: https://android.googlesource.com/platform/external/skia/+/refs/tags/android-9.0.0_r61/Android.bp#940

That's not the solution in this case, since this is a minimal manifest which doesn't sync any repos not needed for TWRP.
