### ISSUE TITLE
libxml2 is removed

### ISSUE THREAD

**Issue by cryptomilk** [minimal-manifest-twrp/platform_manifest_twrp_omni#35]
libxml2 is removed but is needed to build xmllint to sanity check manifest.xml in twrp-9.0 branch.

**Comment by MartinX3** [comment]
Hmm.
Yes, then the additional 37.1 MB are useful.
And they doesn't break the recovery/boot build on my system.

Thank you very much!

Fixed in https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/commit/c6d2d23c16c44517d98c7359fe208e8ad0d4768f
