### ISSUE TITLE
bootctrl already defined

### ISSUE THREAD

**Issue by MartinX3** [minimal-manifest-twrp/platform_manifest_twrp_omni#37]
@CaptainThrowback 
Are you sure with https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/commit/fd0c63d40263514345be514f7649d7bfc85c94aa ?
bootctrl is removed by https://github.com/omnirom/android/blob/80d0906cdb0fcccb16213673356e0091e824d4c8/remove.xml#L104 too.

In my case, if I want to compile with my device trees, which are perfectly working on omnirom 9.0, after your commit I get
```
build/make/core/base_rules.mk:260: error: hardware/sony/bootctrl: MODULE.TARGET.SHARED_LIBRARIES.bootctrl.sdm845 already defined by hardware/qcom/bootctrl.
23:10:51 ckati failed with: exit status 1

My device/board/plattform needs https://github.com/omnirom/android_hardware_sony_bootctrl
#### failed to build some targets (28 seconds) ####
```

My device/board/plattform needs https://github.com/omnirom/android_hardware_sony_bootctrl

**Comment by CaptainThrowback** [comment]
Well you have it in your sony repo - I thought most repos were using qcom, not a separate OEM repo with it included? It won't build for other devices without including it. Is the Sony one customized somehow?

**Comment by MartinX3** [comment]
Yes, there are differences.
The sony one is still a "Android.mk", instead of a .bp file and the sony "boot_control.cpp" contains a `vector<string>::iterator string_iter;`.
As far as I know there will be a ".mk to .bp" switch in Android Q.
And the previously removed bootctrl has only a master branch.

I would need to make a second local_manifest only for the minimal twrp sources, since the normal OmniROM removed it, and I can't add "remove project" of already removed projects (if I want to use the full omni sources with the same local_manifest).

In the end it seems that we need `ifeq ($(strip $(TARGET_USES_HARDWARE_QCOM_BOOTCTRL)),true)` in the Android.mk because the official xperia loire plattform devices (sharing repos with the unofficial tama plattform devices) doesn't support bootctrl.

**Comment by MartinX3** [comment]
Wouldn't it be a better solution if the twrp minimal omni manifest users put the bootctrl in their local_manifest until OmniROM adds this repo in the official OmniROM manifest?

**Comment by CaptainThrowback** [comment]
Omni already uses many AOSP/Qcom repos that aren't the OmniROM versions. So I'm not sure what you mean by adding the repo in the official manifest. But go ahead and do what you want. I'm not really going to be maintaining this anymore anyway.

**Comment by MartinX3** [comment]
I don't want to badly criticize your work, I just think that it's easier for people defining bootctrl or who not support it, if they're not forced to use it and that people who need to add it have the freedom to put this repo in their local_manifest.
I mean since it isn't used in the [default omni manifest](https://github.com/omnirom/android/blob/80d0906cdb0fcccb16213673356e0091e824d4c8/remove.xml#L104) it would make trouble using the same local_manifest for omnirom and the omnirom_minima_manifest_twrp.

I would wait until Omnirom removes it from their own manifest, so we can merge it down from omnirom into the minimal manifest and the omnirom users would need to adapt the same changes and not have a special case for the minimal manifest.

**Comment by CaptainThrowback** [comment]
Like I said, you can make whatever changes are needed to fix this. No need for additional comment.

**Comment by MartinX3** [comment]
Okidoki, thank you!

**Comment by MartinX3** [comment]
@seba3567

**Comment by CaptainThrowback** [comment]
This should be fixed now.
