### ISSUE TITLE
whyred cryptfs building error

### ISSUE THREAD

**Issue by mechakotik** [minimal-manifest-twrp/platform_manifest_twrp_omni#41]
ninja: error: '/media/mycat/DATA/ANDROID/twrp-pie/out/target/product/whyred/obj/SHARED_LIBRARIES/libcryptfs_hw_intermediates/export_includes', needed by '/media/mycat/DATA/ANDROID/twrp-pie/out/target/product/whyred/obj/SHARED_LIBRARIES/libcryptfsfde_intermediates/import_includes', missing and no known rule to make it
20:18:56 ninja failed with: exit status 1

**Comment by MartinX3** [comment]
Which devicetree and repo branch here?

**Comment by CaptainThrowback** [comment]
You need to include the TeamWin device_qcom_common in your omni.dependencies, most likely. That has nothing to do with this manifest.

**Comment by mechakotik** [comment]
Thanks a lot!
