### ISSUE TITLE
Unsigned int error

### ISSUE THREAD

**Issue by bombsquat** [minimal-manifest-twrp/platform_manifest_twrp_omni#42]
bootable/recovery/partition.cpp:1497:158: error: format specifies type 'unsigned int' but the argument has type 'unsigned long' [-Werror,-Wformat]]

**Comment by chankruze** [comment]
@bombsquat what was the issue ?
I am getting the same error as below:

```
bootable/recovery/partition.cpp:1497:158: error: format specifies type 'unsigned int' but the argument has type 'unsigned long' [-Werror,-Wformat]
```

**Comment by bombsquat** [comment]
Just remove line number 1497 in bootable/recovery/partition.cpp

**Comment by chankruze** [comment]
@bombsquat It was pretty fast :)
Trying with the changes
Are they going to fix this ? Btw it's just the bigger partion size which  overflowing from int limit to long.

**Comment by MartinX3** [comment]
If maybe no one fixes it because maybe the error is not widely appearing, you may push a fix at this project
https://gerrit.omnirom.org/#/q/project:android_bootable_recovery

The submit instructions are there
https://github.com/omnirom/android

:)
