### ISSUE TITLE
android_system_core cannot be found

### ISSUE THREAD

**Issue by mathiaskivi** [minimal-manifest-twrp/platform_manifest_twrp_omni#45]
android_system_core cannot be found for Android 4.4 branch.

**Comment by mauronofrio** [comment]
actually twrp doesn't support android 4.4, try with teamwin repo: https://github.com/TeamWin/android_system_core

**Comment by CaptainThrowback** [comment]
Can someone submit a PR to adjust the twrp-4.4 branch to point to the TeamWin system_core?

**Comment by mauronofrio** [comment]
i think this can be closed

**Comment by mathiaskivi** [comment]
Yes, seems to be fixed, thank you.
