### ISSUE TITLE
Is twrp-9.0 Minimal?

### ISSUE THREAD

**Issue by opticyclic** [minimal-manifest-twrp/platform_manifest_twrp_omni#50]
From my notes, when I checked out out TWRP 5.1 a couple of years ago with

    repo init -u git://github.com/lj50036/platform_manifest_twrp_omni.git --depth=1 -b twrp-5.1
    repo --time sync --no-clone-bundle -j8

it took ~15 mins, the `.repo` dir was about 1.5 GB in size and the full twrp dir (including the 1.5GB .repo) was about 6.6 GB.

I just did twrp-9.0 with

    repo init -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git --depth=1 -b twrp-9.0
    repo --time sync --no-clone-bundle -j8

It took ~ 1h40m and the `.repo` dir was about 5.2 GB in size and the full twrp dir (including the 5.2 GB .repo) was about 22 GB.

That is a massive difference!

When I look at the manifests in the different branches there are hundreds of lines difference.

Is the twrp-9.0 branch actually minimal or has the source really increased in size by that much over the versions?

Maybe you could add a table of the check out sizes for comparison in the https://github.com/minimal-manifest-twrp/READ_ME_FIRST

**Comment by MartinX3** [comment]
If you find packages we can remove from the minimal manifest without side effects, please create a PR :)
But that the code size raises is normal, the AOSP code base evolves over time and between 5.1 (2015) and 9.0 (2018) are several years difference

About the size comparison, any help would be appreciated :)

Please let me know if you need anything else.
