### ISSUE TITLE
Cannot checkout android_packages_apps_OmniRemote

### ISSUE THREAD

**Issue by Pinkdoge** [minimal-manifest-twrp/platform_manifest_twrp_omni#61]
error: Cannot checkout android_packages_apps_OmniRemote: ManifestInvalidRevisionError: revision android-10 in android_packages_apps_OmniRemote not found
error: in `sync`: revision android-10 in android_packages_apps_OmniRemote not found

**Comment by MartinX3** [comment]
According to https://omnirom.org/#blog in article `Restructuring of repositories posted by maxwen on 2020-04-18` they turned repositories into private mode only usable, if you gave them some personal data and a reason to add you into the OmniROM orga.
But the repos are still clonable from their gerrir.
I will the TWRP team how we'll proceed on this topic. :)

**Comment by MartinX3** [comment]
In the meantime, I hope it is fixed by https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/commit/d8e7a1d09d08b04611a03f04b89763ef181a4517

Please report back, if you get another issue.
