### ISSUE TITLE
Is platform_manifest_twrp_omni still viable? 

### ISSUE THREAD

**Issue by rowanham** [minimal-manifest-twrp/platform_manifest_twrp_omni#64]
I can use repo to download about 3/4 of this project, but then it asks me for my username and password on github, and if I respond correctly I cannot get any further.

**Comment by MartinX3** [comment]
But you don't told us which repos are not downloadable.

**Comment by MartinX3** [comment]
If the problem still happens then because omnirom wants you now to apply for a membership with a reason and your personal data.
