### ISSUE TITLE
能要求给我的手机做个适配的recovery吗？

### ISSUE THREAD

**Issue by rsyeoh** [minimal-manifest-twrp/platform_manifest_twrp_omni#65]
Recently, the economy has been very bad. I even plan to change my mobile phones to those cheap ones of unknown brands. Can I ask for a suitable twrp for me? At least it's a little fun in my mobile phone

**Comment by MartinX3** [comment]
Sadly we can't do anything without getting the hardware.
Either someone will do it and share it (on XDA) or maybe you can achieve it by yourself and share the work. :)
