### ISSUE TITLE
Fix repo init from android 10

### ISSUE THREAD

**Issue by firemax506** [minimal-manifest-twrp/platform_manifest_twrp_omni#66]
Please change the README.md Get Started area codes.

#### repo init -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0-WIP

Without the "WIP" at the end it will cause error

**Comment by MartinX3** [comment]
Yeah, that should be made after the twrp 10 is not WIP anymore

**Comment by ghost** [comment]
> Yeah, that should be made after the twrp 10 is not WIP anymore

What is the meaning of the WIP?

Also I have a problem when I compile recoveryimage. Gonna create a new issue here after fixing .mk file of my device, and I will provide logs here. Also is there any nice command to print out the errors? There is no error when I started to compile bootimage instead of recoveryimage. Sorry for the english

**Comment by ghost** [comment]
> Yeah, that should be made after the twrp 10 is not WIP anymore

Also the android 10 revision or rev or the "r" on the rear of the android 10 is currently at the 39 or "r39". I hope the devs of this repo will add "r39" soon

**Comment by ghost** [comment]
> Yeah, that should be made after the twrp 10 is not WIP anymore

Also some last question. Sorry for trouble.

Can I boot the compiled twrp 9.0 recovery image to Android 10 OS? I already imported the latest Android 10 kernel & vendor binaries. So if I use twrp 9.0 and Android 10 device tree to compile twrp recoveryimage, will it be ok?

**Comment by MartinX3** [comment]
> > Yeah, that should be made after the twrp 10 is not WIP anymore
> 
> Also the android 10 revision or rev or the "r" on the rear of the android 10 is currently at the 39 or "r39". I hope the devs of this repo will add "r39" soon

Thanks for pinging, I rebased the minimal omni now on top of omni r39 and tracked their new calculator app fork.

**Comment by MartinX3** [comment]
> > Yeah, that should be made after the twrp 10 is not WIP anymore
> 
> Also some last question. Sorry for trouble.
> 
> Can I boot the compiled twrp 9.0 recovery image to Android 10 OS? I already imported the latest Android 10 kernel & vendor binaries. So if I use twrp 9.0 and Android 10 device tree to compile twrp recoveryimage, will it be ok?

I use twrp 9.0 in twrp 10.0 as well
https://github.com/MartinX3-AndroidDevelopment-OmniROM/
Look for my `MartinX3/omnirom-9.0_twrp-10.0` for the needed modifications I did
Maybe some helping you if you get trouble.

**Comment by ghost** [comment]
> > > Yeah, that should be made after the twrp 10 is not WIP anymore
> > 
> > 
> > Also some last question. Sorry for trouble.
> > Can I boot the compiled twrp 9.0 recovery image to Android 10 OS? I already imported the latest Android 10 kernel & vendor binaries. So if I use twrp 9.0 and Android 10 device tree to compile twrp recoveryimage, will it be ok?
> 
> I use twrp 9.0 in twrp 10.0 as well
> https://github.com/MartinX3-AndroidDevelopment-OmniROM/
> Look for my `MartinX3/omnirom-9.0_twrp-10.0` for the needed modifications I did
> Maybe some helping you if you get trouble.

Thanks for the help, I really appreciate it! I'try that one when free tine strikes

**Comment by enweazudaniel** [comment]
> > Yeah, that should be made after the twrp 10 is not WIP anymore
> 
> What is the meaning of the WIP?
> 
> Also I have a problem when I compile recoveryimage. Gonna create a new issue here after fixing .mk file of my device, and I will provide logs here. Also is there any nice command to print out the errors? There is no error when I started to compile bootimage instead of recoveryimage. Sorry for the english

WIP means "work in progress"

**Comment by CaptainThrowback** [comment]
twrp-10.0 branch is now active.
