### ISSUE TITLE
Help in building twrp

### ISSUE THREAD

**Issue by roynatech** [minimal-manifest-twrp/platform_manifest_twrp_omni#67]
What does this mean?
![Screenshot from 2020-05-12 20-46-33](https://user-images.githubusercontent.com/65128262/81684296-ce44b700-9491-11ea-9acc-04a0bca91ccf.png)

**Comment by mauronofrio** [comment]
This mean you didn't select a theme for the twrp

**Comment by roynatech** [comment]
Where should I set it on?  It is already set in BoardConfig.mk Where is ui.xml?

**Comment by MartinX3** [comment]
In terminal use `get_build_var varname` to check if it got set.

**Comment by roynatech** [comment]
![Screenshot from 2020-05-12 20-52-21](https://user-images.githubusercontent.com/65128262/81684973-81151500-9492-11ea-8104-eb2c108e1616.png)
When I type that command on cmd opened in twrp source root directory, nothing happens

**Comment by MartinX3** [comment]
Means the variable is empty
Please fix your device tree to get the BoardConfig.mk executed

**Comment by roynatech** [comment]
Can you take a look at my device tree? I don't know much about device trees...
[samsung.zip](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/4615388/samsung.zip)
(I made it with a generator...)

**Comment by MartinX3** [comment]
Please add them to Github and tag me on the TWRP slack.
This bug tracker is only for bug reports and feature requests. :)

**Comment by roynatech** [comment]
How can I do that...? I'm new... Sorry..

**Comment by roynatech** [comment]
I have uploaded it to github but don't know how to tag you..
