### ISSUE TITLE
Cant sync 9.0

### ISSUE THREAD

**Issue by honzapatCZ** [minimal-manifest-twrp/platform_manifest_twrp_omni#68]
For some unknown reason I cannot sync any of these branches
[https://pastebin.com/W3KYHxN6](commands + errors)

**Comment by MartinX3** [comment]
Does it work now?

And did you test it without creating a shallow clone?

**Comment by LgPWNd** [comment]
Checking out projects:  69% (156/225) android_frameworks_averror: Cannot checkou
t android_frameworks_base: ManifestInvalidRevisionError: revision android-9.0 in
 android_frameworks_base not found
error: in `sync`: revision android-9.0 in android_frameworks_base not found


EDIT: NEVERMIND RESYNC FIXED IT

**Comment by MartinX3** [comment]
nice, fixed :D

**Comment by depesh1977** [comment]
`remote: Total 350 (delta 6), reused 6 (delta 6), pack-reused 338        
Fetching projects:  98% (616/627) android_vendor_qcom_opensource_interfacesОпредremote: Total 5581 (delta 0), reused 0 (delta 0), pack-reused 5581        
Fetching projects:  98% (617/627) android_vendor_omniОпределение изменений:  48%Fetching projects:  98% (618/627) android_frameworks_baseОпределение изменений: Определение изменений: 100% (6651960/6651960), готово.
Fetching projects:  98% (619/627) platform/external/linux-kselftest`
I can't download it either. download a full clone.

**Comment by LgPWNd** [comment]
What can I help you with?
