### ISSUE TITLE
such an error during assembly

### ISSUE THREAD

**Issue by Hadenix** [minimal-manifest-twrp/platform_manifest_twrp_omni#69]
`[  9% 1357/14240] Generated: (/home/hadenix/TWRP9/out/target/product/A5_Pro/android-info.txt)
FAILED: /home/hadenix/TWRP9/out/target/product/A5_Pro/android-info.txt 
/bin/bash -c "(build/make/tools/check_radio_versions.py ) && (echo \"board=mt6763\" > /home/hadenix/TWRP9/out/target/product/A5_Pro/android-info.txt )"
  File "build/make/tools/check_radio_versions.py", line 56
    print "*** Error opening \"%s.sha1\"; can't verify %s" % (fn, key)
                                                         ^
SyntaxError: invalid syntax
[  9% 1362/14240] target  C++: libminui <= bootable/recovery/minui/graphics.cpp
ninja: build stopped: subcommand failed.
23:31:32 ninja failed with: exit status 1
`

**Comment by adi8900** [comment]
same and no idea about fix

**Comment by theimpulson** [comment]
TeamWin specific issue. Please open this issue in their respective repository.
