### ISSUE TITLE
[twrp-10.0] Error compiling 

### ISSUE THREAD

**Issue by ghost** [minimal-manifest-twrp/platform_manifest_twrp_omni#70]
Here is the full output error https://pastebin.com/Bb1GY1sE

I'm confused because when I started to make bootimage instead of recoveryimage, bootimage succeeded and recoveryimage failed. I tried to make the file that are missing then re-run and print another error. Please check the error log file txt attached. 
[recoveryimage.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/4756466/recoveryimage.txt)

**Comment by ghost** [comment]
Here is the bootimage output txt
[output.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/4756534/output.txt)

**Comment by ghost** [comment]
here is our device config

[BoardConfig.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/4756538/BoardConfig.txt)
[omni_r1q.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/4756539/omni_r1q.txt)

**Comment by MartinX3** [comment]
`make bootimage` works, because your device has a recovery partition as declared in your device config.
So it just builds a normal bootimage then.

**Comment by mauronofrio** [comment]
Guys please just wait to for android 10 minimal manifest

**Comment by Hadenix** [comment]
I have such an error when building `/EXECUTABLES/recovery_intermediates/import_includes', missing and no known rule to make it
`

**Comment by Hadenix** [comment]
> Guys please just wait to for android 10 minimal manifest

when to expect?

**Comment by masemoel** [comment]
@firemax13 Your error has been fixed days ago...

**Comment by ghost** [comment]
@masemoel thank you for noticing! I already repo synced the TWRP Source. Gonna start to build for my device later. Thanks!

**Comment by MartinX3** [comment]
Seems like it's fixed for @firemax13 :)
