### ISSUE TITLE
fscrypt_policy.h not found

### ISSUE THREAD

**Issue by mrmazakblu** [minimal-manifest-twrp/platform_manifest_twrp_omni#73]
I am build on branch 10.0 . my device tree is not include enough to make encryption work. so I try to build with 

-- TW_INCLUDE_CRYPTO := false

but this give a compile error.... fscrypt_policy.h not found

I asked for help on telegram group, i got a quick answer. A patch in buildable/recovery

 I do not know if the patch is included here. 

https://gerrit.twrp.me/c/android_bootable_recovery/+/2815

**Comment by MartinX3** [comment]
It's not added.
Please comment in the gerrit that he need to rebase his patch.

After it got merged this project will automatically use it, since it uses the twrp project repo the patch is addressed to.

**Comment by shailangsa** [comment]
off topic: where is the telegram channel for TWRP? i can only see one containing news/announcements and not an actual chat room.

**Comment by CaptainThrowback** [comment]
> off topic: where is the telegram channel for TWRP? i can only see one containing news/announcements and not an actual chat room.

There is no official Telegram channel for TWRP.
