### ISSUE TITLE
unable to checkout android_build_soong project using the 8.1 branch

### ISSUE THREAD

**Issue by shailangsa** [minimal-manifest-twrp/platform_manifest_twrp_omni#74]
I'm using

 `repo init -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1` to sync the repo for the 8.1 branch on the omnirom tree

 and then ran

 `repo sync` 

and it was fine until it got to the android_build_soong  project and it started giving error  as shown in https://pastebin.com/jAtTJ52G

`Checking out projects:   5% (7/123) android_builderror: Cannot checkout android_build_soong: GitError: None: remote omnirom does not have refs/heads/android-8.1`

But i went onto the omnirom tree and i can see the android_build_soong  project does have an 8.1 branch as can be seen at https://github.com/omnirom/android_build_soong/tree/android-8.1

So why is this occurring?

**Comment by CaptainThrowback** [comment]
Is this error still occurring? I don't have this issue here.

**Comment by MartinX3** [comment]
@shailangsa if you report back, we can reopen this issue. :)
