### ISSUE TITLE
Build for payton fails, missing many files

### ISSUE THREAD

**Issue by htsmi** [minimal-manifest-twrp/platform_manifest_twrp_omni#76]
I'm attempting to build TWRP 9.0 for Motorola Payton. According to README, I must `repo init` minimal-manifest and `repo sync`, then `lunch omni_<device>-eng` to fetch the device specific repositories. However this fails because roomservice.py attempts to fetch the device tree from OmniRom github rather than TeamWin github which doesn't seem right.

That aside, I can add the line
```
<project path="device/motorola/payton" name="android_device_motorola_payton" remote="TeamWin" revision="android-9.0"/>
```
to my roomservice.xml and sync. But it seems to be missing components and omni.dependencies doesn't give any hints. I added
```
<project path="device/qcom/common" name="android_device_qcom_common" remote="TeamWin" revision="android-9.0"/>
```
just as a guess, but even with that, it doesn't build properly. It builds without error, but when I flash it, it never loads, and upon inspecting the bootimage, I learn that it is missing many files compared with the official image. Here are the files that it should contain but is missing: [missing files.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/5360549/missing.files.txt)

So I'm clearly missing something important but I can't figure out what. I've followed the README step by step. Does `lunch` and `mka bootimage` work out of the box for other devices? Maybe something wrong with my build environment (Ubuntu 20.04, OpenJDK 8)? If it's nothing that simple then I'll add a build log. I did not save the last one.

As an open source project, it would be nice to know specifically how the official TWRP builds are compiled. It all seems pretty opaque to me, to the point that I can't figure out what source code went into them.

**Comment by shailangsa** [comment]
do you have a log of when you synced the repo?

**Comment by CaptainThrowback** [comment]
Try building recoveryimage, not bootimage. That's what the instructions say to do.

EDIT: If you want to see how the official is built, just check Jenkins: https://jenkins.twrp.me/job/payton-prod/lastSuccessfulBuild/consoleFull

**Comment by htsmi** [comment]
Thanks, I'm looking over Jenkins now to compare logs and environment.

I updated my whole system and tried recoveryimage but it has the same issue. But payton is an A/B device without recovery partition so the 9.0 branch readme says I need bootimage, right?

I've gotten logs for each step.

From `repo --event-log=repo-event.log sync` into a new build directory: [repo-event.log](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/5368104/repo-event.log)

Lunch: [lunch.log](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/5368110/lunch.log)

From `mka recoveryimage`: [recoveryimage.log](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/5368116/recoveryimage.log) (restarted once due to something not set right with lunch, then completed without error)

From `mka bootimage`: [bootimage.log](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/5368123/bootimage.log)

Both of them are still missing all the files I mentioned above and I couldn't find an obvious error in the logs.

EDIT: may be wrong about the missing files now that I dig a little deeper. Will update after I try flashing again.

**Comment by htsmi** [comment]
Update: well I feel dumb. I was trying to use the boot.img rather than recovery.img so of course that didn't work properly. recovery.img contains all the files it should. And yes, I needed to run `mka recoveryimage` as they did in Jenkins.

I still don't understand what cases `mka bootimage` applies to, and it would be nice to note that you need to add the proper manifest lines for your TWRP device, but I'll close this as my issue is resolved.

**Comment by MartinX3** [comment]
Probably you miss a flag in your device trees declaring that your recovery is in the bootimage.
I think it was
```
TARGET_NO_RECOVERY := true
BOARD_USES_RECOVERY_AS_BOOT := true
```
