### ISSUE TITLE
Compile ERROR

### ISSUE THREAD

**Issue by Royna2544** [minimal-manifest-twrp/platform_manifest_twrp_omni#77]
As I was trying to compile twrp for my samsung a20e(android 10 currently). Got Compile error. Tried make clean. Didn't work. Tried on other linux. Didn't work either. Have no idea what is going on. Have put ALLOW_MISSING_DEPENDENCIES=true on boardconfig.mk
Device Tree : https://github.com/roynatech2544/A20e_TWRP_OMNI

![Screenshot from 2020-10-18 19-02-14](https://user-images.githubusercontent.com/69458352/96364188-7ca50480-1174-11eb-961d-36c235bafdab.png)

![Screenshot from 2020-10-18 19-06-18](https://user-images.githubusercontent.com/69458352/96364320-0b198600-1175-11eb-8cc5-8f4b42d4fdbb.png)

![Screenshot from 2020-10-18 19-10-27](https://user-images.githubusercontent.com/69458352/96364431-9bf06180-1175-11eb-8d6a-98316d283325.png)

**Comment by MartinX3** [comment]
1. Use the markdown code formatting for logs or a log file for bigger logs
1. You should probably add missing dependencies according to the error message

**Comment by Royna2544** [comment]
I can't find about those dependencies on google, neither is a downloadable dependency using apt

**Comment by Royna2544** [comment]
error.log on /out :
FAILED: //frameworks/base:ext for turbine [common]
Outputs: /home/royna/Desktop/TWRP/out/soong/.intermediates/frameworks/base/ext/android_common/turbine-combined/ext.jar
Error: exited with code: 1
Command: echo "module ext missing dependencies: libphonenumber-platform, nist-sip, tagsoup, libtextclassifier-java" && false
Output:
module ext missing dependencies: libphonenumber-platform, nist-sip, tagsoup, libtextclassifier-java

**Comment by MartinX3** [comment]
> I can't find about those dependencies on google, neither is a downloadable dependency using apt

You won't find packets in the linux app repository, which are part of the aosp source code.

> error.log on /out :
> FAILED: //frameworks/base:ext for turbine [common]
> Outputs: /home/royna/Desktop/TWRP/out/soong/.intermediates/frameworks/base/ext/android_common/turbine-combined/ext.jar
> Error: exited with code: 1
> Command: echo "module ext missing dependencies: libphonenumber-platform, nist-sip, tagsoup, libtextclassifier-java" && false
> Output:
> module ext missing dependencies: libphonenumber-platform, nist-sip, tagsoup, libtextclassifier-java

You should look where these packets are requested in the aosp source code, maybe these packets are incomplete.
A full OmniROM download is a good reference to look which packets are missing.

**Comment by Royna2544** [comment]
Thank you for the info. I will search it now
P.S. Did lineage 17 source code dropped support in building twrp? Setting Recovery_variant in boardconfig.mk didn't build twrp

**Comment by CaptainThrowback** [comment]
> error.log on /out :
> FAILED: //frameworks/base:ext for turbine [common]
> Outputs: /home/royna/Desktop/TWRP/out/soong/.intermediates/frameworks/base/ext/android_common/turbine-combined/ext.jar
> Error: exited with code: 1
> Command: echo "module ext missing dependencies: libphonenumber-platform, nist-sip, tagsoup, libtextclassifier-java" && false
> Output:
> module ext missing dependencies: libphonenumber-platform, nist-sip, tagsoup, libtextclassifier-java

https://gerrit.twrp.me/#/c/2856

EDIT: I just noticed that I accidentally pushed a patch that removed these repos after I had added them, to test the above patch. I never intended to push that, which is why you're seeing those errors now. I'll fix it later, but in the meantime, picking that patch from Gerrit should make those repos unnecessary (I think). You could also revert this patch: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/commit/dd977c821efb30777ee7a1b57ebbdbddf5dbd79f and then do a repo sync and it should take care of it.

**Comment by Royna2544** [comment]
Umm.. Sorry. But how do I revert a patch in repo?

**Comment by MartinX3** [comment]
> Umm.. Sorry. But how do I revert a patch in repo?

Please apply the patch
The gerrit interface will give you a apply bash command.

Or just `git revert id`

**Comment by viktorxda** [comment]
> https://gerrit.twrp.me/#/c/2856
I can confirm that this commit fixes the mentioned issue.

**Comment by Royna2544** [comment]
Okay That patch worked. Thanks for everyone who had helped me.

**Comment by CaptainThrowback** [comment]
I reverted that accidental commit, so the tree should work fine now without that patch from Gerrit (which I don't think will be merged).
