### ISSUE TITLE
Android 9/10 branch situation

### ISSUE THREAD

**Issue by raphaelthegreat** [minimal-manifest-twrp/platform_manifest_twrp_omni#79]
Hello, I am an android developer and l like building TWRP/custom roms from time to time. My device is not very well supported (Nokia 8), but it does have an official TWRP tree, which however is very old, broken and outdated (https://github.com/TeamWin/android_device_nokia_NB1). I recently read the announcement of the TWRP 3.5.0-0 release, where bigbiff stated that "The separation became apparent when a lot of functionality was dropped in the android-10 release last year.". My device launched with Nougat so it does not support dynamic partitions. Because I think newer is always better, I started work a few months ago to bringup the twrp-10.0 branch for my device (https://github.com/GPUCode/android_device_nokia_nb1_TWRP). However, this announcement says that all devices launched before android 10 should build with the android 9.0 branch (or so I think?). Can someone more knowledgeable, explain the branch situation to me and answer some of these questions:

- Is it worth it, for any device that did not launch with A10 to build on the twrp 10 branch?
- What functionality does twrp-10 lose over twrp-9?
- If the twrp-10 branch is meant only for devices with dynamic partitions, does that mean that every other device will be stuck on twrp-9.0 forever?

**Comment by CaptainThrowback** [comment]
We will be actively maintaining both the 9.0 & 10.0 branches (for now). We've been mirroring updates to both, so you should ONLY update to using the 10.0 branch if your device uses dynamic partitions. Otherwise, continuing to use the 9.0 branch should work just fine. The release on both branches will be incremented at the same time, with the base branch being added to the version number to easily identify it.

**Comment by raphaelthegreat** [comment]
Thanks for the clarification. So I should go back to twrp-9.0 then. Do  you plan to update the twrp-9.0 branch to newer android versions in the future? TWRP 10.0 had some big changes in the recovery environment and many binaries where moved out of /sbin. Do you plan to port changes like these?

**Comment by CaptainThrowback** [comment]
> Thanks for the clarification. So I should go back to twrp-9.0 then. Do  you plan to update the twrp-9.0 branch to newer android versions in the future?

Backwards compatibility is no longer easily maintainable with the changes for dynamic partitions in 10.0. That's the reason that the tree was split, and it's expected to stay that way. The current android-9.0 branch already supports decryption on Android 11, so I'm not sure I fully understand what you're asking.
