### ISSUE TITLE
missing and no known rule to make it

### ISSUE THREAD

**Issue by Lmzaxx** [minimal-manifest-twrp/platform_manifest_twrp_omni#91]
/root/twrp/out/build-omni_shark-package.ninja is missing, regenerating...
[ 99% 398/400] initializing packaging system ...
[ 99% 399/400] including distdir.mk ...
[100% 400/400] writing packaging rules ...
Starting ninja...
FAILED: ninja: '/root/twrp/out/target/product/shark/obj/STATIC_LIBRARIES/bootctrl.sdm845_intermediates/export_includes', needed by '/root/twrp/out/target/product/shark/obj/SHARED_LIBRARIES/android.hardware.boot@1.0-impl-wrapper.recovery_intermediates/import_includes', missing and no known rule to make it

**Comment by MartinX3** [comment]
No device tree, no terminal input before compiling.

**Comment by Lmzaxx** [comment]
What to do without device tree

**Comment by MartinX3** [comment]
Without a device tree you're unable to compile twrp, since it does not know for which devicet build it.

**Comment by Lmzaxx** [comment]
How is that new mobile phone device tree made?

**Comment by MartinX3** [comment]
Handmade by twrp / custom rom maintainers.

**Comment by Lmzaxx** [comment]
Is there a place to study

**Comment by MartinX3** [comment]
Yes, the zulip link in our readme. :)

**Comment by Lmzaxx** [comment]
Can you give me a link directly?I can't find it because I don't know English at all, thank you

**Comment by MartinX3** [comment]
It's contact link in the project readme :)

(And there english the the only allowed language, because otherwise we would have  chaos there.)

**Comment by Lmzaxx** [comment]
I don't know where to order after I go in!

(it doesn't matter, I have a translator 0.0)
