### ISSUE TITLE
TWRP Touch Not Working

### ISSUE THREAD

**Issue by AR1Ablock** [minimal-manifest-twrp/platform_manifest_twrp_omni#92]
Thanks For This minimal Source Code Of TWRP.

BUT I am facing above Issue 👆.

I have made 2 TWRP Android 10 based Builds For 2 Different Kinds of phone Models Of Infinix.

Both have Touch not working issue.

Is this related to Android 10 twrp source code or Phone kernel has disabled twrp touch?

**Comment by MartinX3** [comment]
You're welcome.

Sadly there are no logs and device trees.
