### ISSUE TITLE
Build Failed at 99%

### ISSUE THREAD

**Issue by bhawesh2002** [minimal-manifest-twrp/platform_manifest_twrp_omni#93]
I am compiling twrp for Motorola Moto g(40) fusion codenamed '**haniop**'. 
I executed commands sequientially and the last command "mka bootimage" ended with an error:
[ 99% 102/103] finishing build rules ...
FAILED: 
build/make/core/tasks/platform_availability_check.mk:33: warning:  Following modules are requested to be installed. But are not available for platform because they do not have "//apex_available:platform"
 or they depend on other modules that are not available for platform
Offending entries:
libicui18n:external/icu/icu4c/source/i18n
libicui18n_32:external/icu/icu4c/source/i18n
In file included from build/make/core/main.mk:1327:
In file included from build/make/core/Makefile:5574:
build/make/core/tasks/platform_availability_check.mk:33: error: Build failed.
20:03:18 ckati failed with: exit status 1

#### failed to build some targets (03:27 (mm:ss)) ####

Here is the entire image
 

![Screenshot from 2021-10-31 20-03-28](https://user-images.githubusercontent.com/55053472/139588872-37a73af1-4465-41cf-990f-a8c363c230b9.png)

I dont understand why I get this error ??

**Comment by MartinX3** [comment]
Please link your device trees in the issue ticket next time.

https://github.com/bhawesh2002/android_device_motorola_haniop
https://github.com/bhawesh2002/android_vendor_motorola_haniop

**Comment by bhawesh2002** [comment]
Thank you @MartinX3  to link my device trees.
Can you tell me why I get this error???

Error:
[ 99% 102/103] finishing build rules ...
FAILED:
build/make/core/tasks/platform_availability_check.mk:33: warning: Following modules are requested to be installed. But are not available for platform because they do not have "//apex_available:platform"
or they depend on other modules that are not available for platform
Offending entries:
libicui18n:external/icu/icu4c/source/i18n
libicui18n_32:external/icu/icu4c/source/i18n
In file included from build/make/core/main.mk:1327:
In file included from build/make/core/Makefile:5574:
build/make/core/tasks/platform_availability_check.mk:33: error: Build failed.
20:03:18 ckati failed with: exit status 1

**Comment by bhawesh2002** [comment]
Fixed the issue
