### ISSUE TITLE
TWRP Touch screen doesn't work (Nokia 5.1)

### ISSUE THREAD

**Issue by wooter6928196219911** [minimal-manifest-twrp/platform_manifest_twrp_omni#95]
Hello, I built TWRP for my device (Nokia 5.1) and there's the issue though and that's the touch screen, Upon entering TWRP, I can't swipe or do anything without a USB Mouse

Anyway, here's the kernel (Since the device tree is BUILT into it) and dmesg log
[Image.gz](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/7823504/Image.gz)
[dmesg_log.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/files/7823511/dmesg_log.txt)

**Comment by CaptainThrowback** [comment]
Not a manifest issue.
