### ISSUE TITLE
Build error.

### ISSUE THREAD

**Issue by ycly2333** [minimal-manifest-twrp/platform_manifest_twrp_omni#98]
I built twrp for my device recently, but it give an error.
But I didn't get this error when I built last month.
Build machine:GitHub action with Ubuntu 18.04&PC with Ubuntu 22.04
(Two machines got the same error about the "python3_twrp")
Log:
Starting build with ninja
ninja: Entering directory `.'
ninja: error: 'python3_twrp', needed by '/home/runner/work/Action-Recovery-builder/Action-Recovery-builder/workspace/out/target/product/S1S/obj/EXECUTABLES/recovery_intermediates/twrp.o', missing and no known rule to make it
build/core/ninja.mk:157: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1
Error: Process completed with exit code 2.

**Comment by CaptainThrowback** [comment]
Sorry, I have to update the minimal manifests for this. Will work on that later. Thanks for the report.

**Comment by CaptainThrowback** [comment]
This should be fixed now. Please confirm and close.

**Comment by ycly2333** [comment]
I am trying it now,and I will reply you after 15 minutes.
![Screenshot_20220704-013058_Chrome](https://user-images.githubusercontent.com/56163845/177050892-e9cd4f98-9a26-46b5-99f8-ec16900374f1.png)

**Comment by ycly2333** [comment]
The problem was solved, thank you.

**Comment by ycly2333** [comment]
The problem was solved, thank you.
