### ISSUE TITLE
Must be built with python2

### ISSUE THREAD

**Issue by rumplestilzken** [minimal-manifest-twrp/platform_manifest_twrp_omni#99]
I did not see any indication about building with only python2. Because of syntax changes between python2 and python3, this must be built from the ground up using python2. Often requiring the python symlink to be replaced from the systems existing python3 implementation. This should be added somewhere in the documentation as someone who is not familiar or has not done the digging to become familiar with the presented issue may have a hard time understanding why they are getting a syntax error, specifically with Version.inc.in in my case. I built with python3 and it gets to this error. If i then build with python2 i get a compliation error from one of the generated classes i believe. Building from ground up with python2 presents no issues.

**Comment by MartinX3** [comment]
Like this?
https://source.android.com/setup/build/initializing

**Comment by rumplestilzken** [comment]
That documentation specifically says python2 has been deprecated and to use python3, but this project does not build with python3, as stated in my OP.

**Comment by MartinX3** [comment]
It's deprecated since 1.1.2020

That means every Android version since 2020 needs python 3 to build
2020 came Android 11
2019 came Android 10

So it's logically that you need python 2.x for such an old android

If you want you could create a PR with a nice warning.
I think in my own opinion that the aosp documentation is enough information for developers.

**Comment by rumplestilzken** [comment]
So just create a pull request to modify the README.md to include a note about the discrepencies in python version? I'm new to how github works and more specifically how a project would go about warning about something like this? If you give me a direction, i can follow through with it pretty well.

**Comment by MartinX3** [comment]
Luckily it's easy with GitHub
Just open the readme.md and click on the pencil
And choose a useful title and maybe commit description

The file code is markdown

Thank you :)

**Comment by rumplestilzken** [comment]
Have created pull request, thanks for your help. Will close this ticket now.
